name: tests-environment
channels:
  - defaults
  - conda-forge
dependencies:
  - coverage
  - pytest
  - mpi4py
  - openmpi
  - pip
  - pip:
    - cobaya
    - flake8
    - flaky
    - pytest-xdist
    - pytest-cov
